name: Sphinx Action
on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Build Documentation
        run: |
          cd docs
          sphinx-apidoc -o source ../galaxy
          sphinx-apidoc -o source ../API
          make html

      - name: Debug Output
        run: |
          ls -la ./docs/build/html

      - name: Deploy HTML
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          publish_branch: gh-pages
